### ISSUE TITLE
"Inflammable" semantic error

### ISSUE THREAD

**Issue by Alexander3847575** [acikek/hazard-diamond#1]
Adding Hazard data via Datapacks > JSON Data > Format > Quadrants > Table

Fire Hazard value 0 should be "non-inflammable", as inflammable means able to inflame, or to able to set on fire.

Similarly, flammable wasn't *technically* a verb, but has become common usage, even though it has no relation to the verb "to flame". This isn't a huge deal, but the distinction can be dangerous in real life, so I found the mistake ironic :p

**Comment by acikek** [comment]
Thanks for the corrections. I've updated the term to say "nonflammable". The mod version has also been updated to `1.0.1` and includes those fixes. I decided to keep the GHS pictogram as "flammable" as that's what the standard calls it.
